package com.today.api.user.response

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 用户登录返回体

        **/
        case class LoginUserResponse(

         /**
        *

 用户名称

        **/
        
        userName : String, /**
        *

 电话号码

        **/
        
        telephone : String, /**
        *

 用户状态

        **/
        
        status : com.today.api.user.enums.UserStatusEnum, /**
        *

 用户 积分

        **/
        
        integral : Int, /**
        *

 注册时间

        **/
        
        createdAt : Long, /**
        *

 更新时间

        **/
        
        updatedAt : Long, /**
        *

 用户邮箱

        **/
        
        email : Option[String] = None, /**
        *

 用户 qq

        **/
        
        qq : Option[String] = None
        )
      