 package com.today.api.user.request.serializer;

        import com.today.api.user.request.serializer._;import com.today.api.user.response.serializer._;
        import com.isuwang.dapeng.core._
        import com.isuwang.org.apache.thrift._
        import com.isuwang.org.apache.thrift.protocol._

        /**
        * Autogenerated by Dapeng-Code-Generator (1.2.2)
        *
        * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
        *  @generated
        **/

        class LoginUserRequestSerializer extends TCommonBeanSerializer[com.today.api.user.request.LoginUserRequest]{
          
      @throws[TException]
      override def read(iprot: TProtocol): com.today.api.user.request.LoginUserRequest = {

        var schemeField: com.isuwang.org.apache.thrift.protocol.TField = null
        iprot.readStructBegin()

      var passWord: String = null
        var telephone: String = null
        

      while (schemeField == null || schemeField.`type` != com.isuwang.org.apache.thrift.protocol.TType.STOP) {

        schemeField = iprot.readFieldBegin

        schemeField.id match {
          
              case 1 =>
                  schemeField.`type` match {
                    case com.isuwang.org.apache.thrift.protocol.TType.STRING => passWord = iprot.readString
                    case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
            }
            
              case 2 =>
                  schemeField.`type` match {
                    case com.isuwang.org.apache.thrift.protocol.TType.STRING => telephone = iprot.readString
                    case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
            }
            
          case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
        }
      }

      iprot.readFieldEnd
      iprot.readStructEnd

      val bean = com.today.api.user.request.LoginUserRequest(passWord = passWord,telephone = telephone)
      validate(bean)

      bean
      }
    
      @throws[TException]
      override def write(bean: com.today.api.user.request.LoginUserRequest, oprot: TProtocol): Unit = {

      validate(bean)
      oprot.writeStructBegin(new com.isuwang.org.apache.thrift.protocol.TStruct("LoginUserRequest"))

      
            {
            val elem0 = bean.passWord 
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("passWord", com.isuwang.org.apache.thrift.protocol.TType.STRING, 1.asInstanceOf[Short]))
            oprot.writeString(elem0)
            oprot.writeFieldEnd
            
            }
            {
            val elem1 = bean.telephone 
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("telephone", com.isuwang.org.apache.thrift.protocol.TType.STRING, 2.asInstanceOf[Short]))
            oprot.writeString(elem1)
            oprot.writeFieldEnd
            
            }
      oprot.writeFieldStop
      oprot.writeStructEnd
    }
    
      @throws[TException]
      override def validate(bean: com.today.api.user.request.LoginUserRequest): Unit = {
      
              if(bean.passWord == null)
              throw new SoaException(SoaBaseCode.NotNull, "passWord字段不允许为空")
            
              if(bean.telephone == null)
              throw new SoaException(SoaBaseCode.NotNull, "telephone字段不允许为空")
            
    }
    

          @throws[TException]
          override def toString(bean: com.today.api.user.request.LoginUserRequest): String = if (bean == null) "null" else bean.toString

        }
        
      