 package com.today.api.user.request.serializer;

        import com.today.api.user.request.serializer._;import com.today.api.user.response.serializer._;
        import com.isuwang.dapeng.core._
        import com.isuwang.org.apache.thrift._
        import com.isuwang.org.apache.thrift.protocol._

        /**
        * Autogenerated by Dapeng-Code-Generator (1.2.2)
        *
        * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
        *  @generated
        **/

        class ModifyUserRequestSerializer extends TCommonBeanSerializer[com.today.api.user.request.ModifyUserRequest]{
          
      @throws[TException]
      override def read(iprot: TProtocol): com.today.api.user.request.ModifyUserRequest = {

        var schemeField: com.isuwang.org.apache.thrift.protocol.TField = null
        iprot.readStructBegin()

      var email: String = null
        var qq: String = null
        var userId: String = null
        

      while (schemeField == null || schemeField.`type` != com.isuwang.org.apache.thrift.protocol.TType.STOP) {

        schemeField = iprot.readFieldBegin

        schemeField.id match {
          
              case 1 =>
                  schemeField.`type` match {
                    case com.isuwang.org.apache.thrift.protocol.TType.STRING => email = iprot.readString
                    case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
            }
            
              case 2 =>
                  schemeField.`type` match {
                    case com.isuwang.org.apache.thrift.protocol.TType.STRING => qq = iprot.readString
                    case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
            }
            
              case 3 =>
                  schemeField.`type` match {
                    case com.isuwang.org.apache.thrift.protocol.TType.STRING => userId = iprot.readString
                    case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
            }
            
          case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
        }
      }

      iprot.readFieldEnd
      iprot.readStructEnd

      val bean = com.today.api.user.request.ModifyUserRequest(email = email,qq = qq,userId = userId)
      validate(bean)

      bean
      }
    
      @throws[TException]
      override def write(bean: com.today.api.user.request.ModifyUserRequest, oprot: TProtocol): Unit = {

      validate(bean)
      oprot.writeStructBegin(new com.isuwang.org.apache.thrift.protocol.TStruct("ModifyUserRequest"))

      
            {
            val elem0 = bean.email 
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("email", com.isuwang.org.apache.thrift.protocol.TType.STRING, 1.asInstanceOf[Short]))
            oprot.writeString(elem0)
            oprot.writeFieldEnd
            
            }
            {
            val elem1 = bean.qq 
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("qq", com.isuwang.org.apache.thrift.protocol.TType.STRING, 2.asInstanceOf[Short]))
            oprot.writeString(elem1)
            oprot.writeFieldEnd
            
            }
            {
            val elem2 = bean.userId 
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("userId", com.isuwang.org.apache.thrift.protocol.TType.STRING, 3.asInstanceOf[Short]))
            oprot.writeString(elem2)
            oprot.writeFieldEnd
            
            }
      oprot.writeFieldStop
      oprot.writeStructEnd
    }
    
      @throws[TException]
      override def validate(bean: com.today.api.user.request.ModifyUserRequest): Unit = {
      
              if(bean.email == null)
              throw new SoaException(SoaBaseCode.NotNull, "email字段不允许为空")
            
              if(bean.qq == null)
              throw new SoaException(SoaBaseCode.NotNull, "qq字段不允许为空")
            
              if(bean.userId == null)
              throw new SoaException(SoaBaseCode.NotNull, "userId字段不允许为空")
            
    }
    

          @throws[TException]
          override def toString(bean: com.today.api.user.request.ModifyUserRequest): String = if (bean == null) "null" else bean.toString

        }
        
      