package com.today.api.user.request

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 记录请求流水接口

        **/
        case class ChangeIntegralRequest(

         /**
        *

 用户 id

        **/
        
        userId : String, /**
        *

  该流水涉及到的积分数(可正可负)

        **/
        
        integralPrice : String, /**
        *

  积分流水类型

        **/
        
        integralType : com.today.api.user.enums.IntegralTypeEnum, /**
        *

  积分改变的来源

        **/
        
        integralSource : com.today.api.user.enums.IntegralSourceEnum
        )
      