package com.today.api.user.request

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 冻结操作请求体

        **/
        case class FreezeUserRequest(

         /**
        *

 用户 id

        **/
        
        userId : String, /**
        *

  操作员冻结备注

        **/
        
        remark : String
        )
      