package com.today.api.user.request

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 修改用户请求体

        **/
        case class ModifyUserRequest(

         /**
        *

 用户邮箱

        **/
        
        email : String, /**
        *

 用户 qq

        **/
        
        qq : String
        )
      