package com.today.api.user.request

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 注册用户请求体

        **/
        case class RegisterUserRequest(

         /**
        *

 用户名称

        **/
        
        userName : String, /**
        *

 密码

        **/
        
        passWord : String, /**
        *

 电话号码

        **/
        
        telephone : String
        )
      